export const COUNTRIES = [
  {
    code: 'US',
    name: 'United States',
    countryCities: [
      { code: 'NYC', name: 'New York City' },
      { code: 'LA', name: 'Los Angeles' },
      { code: 'CHI', name: 'Chicago' },
      { code: 'HOU', name: 'Houston' },
      { code: 'MIA', name: 'Miami' },
      { code: 'DAL', name: 'Dallas' },
      { code: 'SFO', name: 'San Francisco' },
      { code: 'SEA', name: 'Seattle' },
      { code: 'ATL', name: 'Atlanta' },
      { code: 'DEN', name: 'Denver' },
    ],
  },
  {
    code: 'CA',
    name: 'Canada',
    countryCities: [
      { code: 'TOR', name: 'Toronto' },
      { code: 'VAN', name: 'Vancouver' },
      { code: 'MTL', name: 'Montreal' },
      { code: 'CAL', name: 'Calgary' },
      { code: 'EDM', name: 'Edmonton' },
      { code: 'OTT', name: 'Ottawa' },
      { code: 'WPG', name: 'Winnipeg' },
      { code: 'HAL', name: 'Halifax' },
      { code: 'QUE', name: 'Quebec City' },
      { code: 'SAS', name: 'Saskatoon' },
    ],
  },
  {
    code: 'UK',
    name: 'United Kingdom',
    countryCities: [
      { code: 'LON', name: 'London' },
      { code: 'MAN', name: 'Manchester' },
      { code: 'EDI', name: 'Edinburgh' },
      { code: 'GLA', name: 'Glasgow' },
      { code: 'BIR', name: 'Birmingham' },
      { code: 'LIV', name: 'Liverpool' },
      { code: 'NCL', name: 'Newcastle' },
      { code: 'LEI', name: 'Leicester' },
      { code: 'SHE', name: 'Sheffield' },
      { code: 'BRIS', name: 'Bristol' },
    ],
  },
  {
    code: 'FR',
    name: 'France',
    countryCities: [
      { code: 'PAR', name: 'Paris' },
      { code: 'MAR', name: 'Marseille' },
      { code: 'LYO', name: 'Lyon' },
      { code: 'BOR', name: 'Bordeaux' },
      { code: 'TLS', name: 'Toulouse' },
      { code: 'NCE', name: 'Nice' },
      { code: 'STR', name: 'Strasbourg' },
      { code: 'REN', name: 'Rennes' },
      { code: 'LIL', name: 'Lille' },
      { code: 'TOU', name: 'Toulon' },
    ],
  },
  {
    code: 'DE',
    name: 'Germany',
    countryCities: [
      { code: 'BER', name: 'Berlin' },
      { code: 'HAM', name: 'Hamburg' },
      { code: 'MUN', name: 'Munich' },
      { code: 'FRA', name: 'Frankfurt' },
      { code: 'DUS', name: 'Dusseldorf' },
      { code: 'KOL', name: 'Cologne' },
      { code: 'STU', name: 'Stuttgart' },
      { code: 'LEI', name: 'Leipzig' },
      { code: 'DOR', name: 'Dortmund' },
      { code: 'HAN', name: 'Hanover' },
    ],
  },
  {
    code: 'IT',
    name: 'Italy',
    countryCities: [
      { code: 'ROM', name: 'Rome' },
      { code: 'MIL', name: 'Milan' },
      { code: 'NAP', name: 'Naples' },
      { code: 'FLO', name: 'Florence' },
      { code: 'VEN', name: 'Venice' },
      { code: 'TUR', name: 'Turin' },
      { code: 'PAL', name: 'Palermo' },
      { code: 'GEN', name: 'Genoa' },
      { code: 'BOG', name: 'Bologna' },
      { code: 'TIR', name: 'Trieste' },
    ],
  },
  {
    code: 'JP',
    name: 'Japan',
    countryCities: [
      { code: 'TOK', name: 'Tokyo' },
      { code: 'OSA', name: 'Osaka' },
      { code: 'KYT', name: 'Kyoto' },
      { code: 'SAP', name: 'Sapporo' },
      { code: 'FUK', name: 'Fukuoka' },
      { code: 'NAG', name: 'Nagoya' },
      { code: 'HIK', name: 'Hiroshima' },
      { code: 'NAR', name: 'Nara' },
      { code: 'KOB', name: 'Kobe' },
      { code: 'SEN', name: 'Sendai' },
    ],
  },
  {
    code: 'AU',
    name: 'Australia',
    countryCities: [
      { code: 'SYD', name: 'Sydney' },
      { code: 'MEL', name: 'Melbourne' },
      { code: 'BRI', name: 'Brisbane' },
      { code: 'PER', name: 'Perth' },
      { code: 'ADE', name: 'Adelaide' },
      { code: 'CAN', name: 'Canberra' },
      { code: 'GOL', name: 'Gold Coast' },
      { code: 'NEW', name: 'Newcastle' },
      { code: 'HOB', name: 'Hobart' },
      { code: 'DAR', name: 'Darwin' },
    ],
  },
  {
    code: 'CN',
    name: 'China',
    countryCities: [
      { code: 'PEK', name: 'Beijing' },
      { code: 'SHA', name: 'Shanghai' },
      { code: 'CAN', name: 'Guangzhou' },
      { code: 'SZX', name: 'Shenzhen' },
      { code: 'CTU', name: 'Chengdu' },
      { code: 'XIY', name: 'Xian' },
      { code: 'HKG', name: 'Hong Kong' },
      { code: 'WUH', name: 'Wuhan' },
      { code: 'CSX', name: 'Changsha' },
      { code: 'KMG', name: 'Kunming' },
    ],
  },
];



